# 1. 让 BitBake 能找到这个层
BBPATH .= ":${LAYERDIR}"

# 2. 告诉 BitBake 解析哪些配方文件
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# 3. 给这个层起个名字叫 "embedlab"
BBFILE_COLLECTIONS += "TinyAI"

# 4. 匹配规则：路径以层目录开头的文件都属于 embedlab 层
BBFILE_PATTERN_embedlab = "^${LAYERDIR}/"

# 5. 优先级设为 6（高于默认的 5）
BBFILE_PRIORITY_embedlab = "6"

# 6. 这个层依赖 OE-Core 的 meta 层
LAYERDEPENDS_embedlab = "core"

# 7. 兼容 Yocto Scarthgap (5.0 LTS) 版本
LAYERSERIES_COMPAT_embedlab = "scarthgap"

# 8. 自定义变量：产品版本号
EMBEDLAB_VERSION = "1.0.0"
